#!/usr/bin/env python3.12
import argparse
import os
import json
import logging
import subprocess
from datetime import datetime
from pathlib import Path

from pystac import Catalog, ItemCollection

LOG = logging.getLogger("viirsl1")


def run(cmd, **kwds) -> subprocess.CompletedProcess:
    kwds.setdefault("check", True)
    cmd = [str(x) for x in cmd]
    LOG.info("%s", " ".join(cmd))
    try:
        return subprocess.run(cmd, **kwds)
    except subprocess.CalledProcessError as e:
        LOG.warning(f"viirls1 {e}")
        return subprocess.CompletedProcess


def gather_catalog_inputs(fpath: Path, roles: list[str]) -> list[Path]:
    """Gather input file paths from STAC catalog inputs.

    Assumes the asset hrefs are local.
    """
    LOG.info("splitting %s", fpath)
    output_paths = []
    data = json.load(fpath.open())
    if data.get("type", "") == "FeatureCollection":
        avail_items = ItemCollection.from_dict(data).items
    else:
        avail_items = Catalog.from_dict(data, href=str(fpath)).get_items(recursive=True)
    for item in avail_items:
        LOG.debug(item)
        for asset in item.assets.values():
            if not set(asset.roles or []) & set(roles):
                LOG.debug(
                    "skipping item %s asset role %s href %s",
                    item.id,
                    asset.roles,
                    asset.href,
                )
                continue
            if asset.href.startswith("/"):
                path = Path(asset.href)
            else:
                path = fpath.parent / Path(asset.href).name
            if not path.exists():
                LOG.warning(
                    "Item %s asset role %s href %s does not exist locally",
                    item.id,
                    asset.roles,
                    path,
                )
                continue
            output_paths.append(path)
    return output_paths


def run_l1a(granule, apid826, apid0, apid8, apid11):
    cmd = (
        "viirsl1",
        "noaa20",
        "l1a",
        str(apid826),
        str(apid11),
        str(apid8),
        str(apid0),
    )
    LOG.info(f"running: {' '.join(cmd)}")
    run(cmd)
    l1a_fn = list(Path("./").glob(f"V{granule:%Y%j%H%M}*L1A*.nc"))
    assert len(l1a_fn) == 1
    l1a_fn = l1a_fn[0]
    LOG.info(f"{l1a_fn=}")
    collection = "002"
    out_fn = f"VJ101.A{granule:%Y%j.%H%M}.{collection}.{datetime.now().strftime('%Y%j%H%M%S')}.nc"
    os.rename(l1a_fn, out_fn)
    LOG.info(f"L1A created: {out_fn}")


def main(
    granule: datetime,
    collection_id: str,
    apid826: Path,
    apid11: Path,
    apid8: Path,
    apid0: Path,
    destdir: Path,
    file_duration: int,
    roles: list[str] | None = None,
):
    LOG.info("starting viirsl1")

    run_l1a(granule, apid826, apid0, apid8, apid11)

    run(
        [
            "catgen",
            "--verbose",
            "-t",
            "catalog",
            collection_id,
            f"{destdir}/V*01.A*.nc",
        ],
        check=True,
    )
    run(["ls", "-l"])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument(
        "-d",
        "--file-duration",
        type=int,
        default=360,
        help="File duration in seconds. Files will be aligned to 0z",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("."),
        help="directory to save outputs to",
    )
    parser.add_argument("granule")
    parser.add_argument("collection_id")
    parser.add_argument("apid826")
    parser.add_argument("apid11")
    parser.add_argument("apid8")
    parser.add_argument("apid0")

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO, format="%(message)s"
    )

    granule = datetime.strptime(args.granule, "%Y-%m-%dT%H:%M:%SZ")
    main(
        granule,
        args.collection_id,
        args.apid826,
        args.apid11,
        args.apid8,
        args.apid0,
        file_duration=args.file_duration,
        destdir=args.output,
        roles=["data"],
    )
